create table rule_engine_condition
(
    id               int auto_increment
        primary key,
    name             varchar(50)   not null,
    description      varchar(500)  null,
    workspace_id     int           null,
    create_user_id   int           null,
    create_user_name varchar(50)   null,
    left_type        tinyint       null,
    left_value       varchar(2000) null,
    left_value_type  varchar(20)   not null,
    right_type       tinyint       null,
    right_value_type varchar(20)   not null,
    right_value      varchar(2000) null,
    symbol           varchar(20)   null,
    update_time      timestamp     null,
    create_time      timestamp     null,
    deleted          tinyint       null
);

create index rule_engine_condition_name_index
    on rule_engine_condition (name);

INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('true', null, 1, null, null, 2, 'true', 'BOOLEAN', 2, 'BOOLEAN', 'true', 'EQ', '2020-09-04 20:50:46', '2020-08-24 15:57:57', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('false', null, 1, null, null, 2, 'true', 'BOOLEAN', 2, 'BOOLEAN', 'false', 'EQ', '2020-08-24 16:26:51', '2020-08-24 16:26:51', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('年龄', null, 1, null, null, 0, '66', 'NUMBER', 2, 'NUMBER', '20', 'GE', '2020-08-27 00:15:15', '2020-08-27 00:15:15', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('vip等级', null, 1, null, null, 0, '67', 'NUMBER', 2, 'NUMBER', '3', 'GE', '2020-08-27 00:15:35', '2020-08-27 00:15:35', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('消费金额', null, 1, null, null, 0, '68', 'NUMBER', 2, 'NUMBER', '30000', 'GE', '2020-08-27 00:17:05', '2020-08-27 00:17:05', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('特殊省份', null, 1, null, null, 2, '北京,河南,上海', 'COLLECTION', 0, 'COLLECTION', '69', 'CONTAIN', '2020-08-27 01:05:05', '2020-08-27 01:05:05', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('文化程度', null, 1, null, null, 2, '博士', 'STRING', 0, 'STRING', '70', 'EQ', '2020-08-27 01:08:04', '2020-08-27 01:08:04', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('特殊市区', null, 1, null, null, 2, '北京市,商丘市', 'COLLECTION', 0, 'STRING', '71', 'CONTAIN', '2020-08-27 01:14:08', '2020-08-27 01:13:05', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('审批人测试', null, 1, null, null, 1, '35', 'COLLECTION', 2, 'NUMBER', '123', 'CONTAIN', '2020-08-27 12:35:57', '2020-08-27 12:35:50', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('测试条件-绝对值', null, 1, null, null, 1, '52', 'NUMBER', 2, 'NUMBER', '123', 'EQ', '2020-08-28 14:48:48', '2020-08-28 14:48:48', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('集合在.测试', null, 1, null, null, 0, '61', 'COLLECTION', 2, 'COLLECTION', '1,2', 'IN', '2020-09-10 18:12:49', '2020-08-28 16:25:44', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('年龄范围条件', null, 1, null, null, 1, '70', 'BOOLEAN', 2, 'BOOLEAN', 'true', 'EQ', '2020-08-30 18:53:37', '2020-08-30 18:53:37', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('年龄大于等于20条件', null, 1, null, null, 0, '66', 'NUMBER', 2, 'NUMBER', '20', 'GE', '2020-08-30 21:25:26', '2020-08-30 21:24:51', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('年龄小于等于26条件', null, 1, null, null, 0, '66', 'NUMBER', 2, 'NUMBER', '26', 'LE', '2020-09-04 20:56:36', '2020-08-30 21:25:18', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('号码开头', null, 1, null, null, 0, '77', 'STRING', 2, 'STRING', '137', 'STARTS_WITH', '2020-09-10 18:08:13', '2020-09-10 18:08:13', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('限制号码长度', null, 1, null, null, 1, '76', 'NUMBER', 2, 'NUMBER', '17', 'LE', '2020-09-10 20:08:15', '2020-09-10 18:11:41', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('排除号码在白名单的', null, 1, null, null, 1, '77', 'COLLECTION', 0, 'STRING', '77', 'CONTAIN', '2020-09-10 23:44:25', '2020-09-10 18:15:27', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('验证是否为手机号码条件', null, 1, null, null, 1, '79', 'BOOLEAN', 2, 'BOOLEAN', 'true', 'EQ', '2020-09-16 14:57:38', '2020-09-16 14:57:38', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('vip等级大于4以上', null, 1, null, null, 0, '67', 'NUMBER', 2, 'NUMBER', '4', 'GT', '2020-11-13 19:14:00', '2020-11-13 19:14:00', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('消费金额大于3000', null, 1, null, null, 0, '68', 'NUMBER', 2, 'NUMBER', '3000', 'GT', '2020-11-13 19:14:33', '2020-11-13 19:14:33', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('定期存款年限在', null, 1, null, null, 2, '0.5', 'NUMBER', 2, 'NUMBER', '1', 'LE', '2020-12-07 11:25:49', '2020-12-07 11:24:38', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('存款年限在', null, 1, null, null, 2, '10', 'NUMBER', 2, 'NUMBER', '2', 'GE', '2020-12-07 13:43:09', '2020-12-07 11:25:26', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('账户最低存款额度', null, 1, null, null, 0, '95', 'NUMBER', 2, 'NUMBER', '2000', 'GT', '2020-12-07 11:27:15', '2020-12-07 11:27:15', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('存款年限', null, 1, null, null, 2, '1', 'NUMBER', 2, 'NUMBER', '2', 'LE', '2020-12-07 16:11:35', '2020-12-07 16:11:35', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('最低存款额度大于等于2000', null, 1, null, null, 0, '95', 'NUMBER', 2, 'NUMBER', '2000', 'GE', '2020-12-07 16:27:39', '2020-12-07 16:27:39', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('定期存款年限', null, 1, null, null, 0, '98', 'NUMBER', 2, 'NUMBER', '1', 'GE', '2020-12-14 04:57:40', '2020-12-07 16:28:24', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('年收入是否大于20万', null, 1, 1, 'dqw', 0, '105', 'NUMBER', 2, 'NUMBER', '200000', 'GE', '2020-12-16 10:37:08', '2020-12-16 10:36:52', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('年收入是否小于26400', '年收入是否小于26400说明', 1, 2, 'lq', 0, '105', 'NUMBER', 2, 'NUMBER', '26400', 'LT', '2020-12-17 07:35:10', '2020-12-17 07:35:10', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('年收入是否大于10000', '年收入是否大于10000说明', 1, 2, 'lq', 0, '105', 'NUMBER', 2, 'NUMBER', '10000', 'GT', '2020-12-17 07:36:44', '2020-12-17 07:36:44', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('性别是男的', null, 1, 1, 'dqw', 0, '114', 'STRING', 2, 'STRING', '男', 'EQ', '2020-12-25 03:19:47', '2020-12-25 03:19:47', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('年龄小于10岁', null, 1, 1, 'dqw', 0, '66', 'NUMBER', 2, 'NUMBER', '10', 'LT', '2020-12-25 03:20:28', '2020-12-25 03:20:28', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('身高170cm以上', null, 1, 1, 'dqw', 0, '115', 'NUMBER', 2, 'NUMBER', '170', 'GE', '2020-12-25 03:51:48', '2020-12-25 03:22:45', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('年级是三年级以上', null, 1, 1, 'dqw', 0, '116', 'NUMBER', 2, 'NUMBER', '3', 'GT', '2020-12-25 03:55:45', '2020-12-25 03:55:45', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('身体是否健壮', null, 1, 1, 'dqw', 2, '健壮,优秀,良好', 'COLLECTION', 0, 'STRING', '117', 'CONTAIN', '2020-12-28 19:23:00', '2020-12-25 04:00:21', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('专业是否为体育生', null, 1, 1, 'dqw', 2, '体育', 'STRING', 0, 'STRING', '119', 'EQ', '2020-12-29 14:12:12', '2020-12-25 04:05:11', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('年龄在7-11之间条件', null, 1, 1, 'dqw', 1, '118', 'BOOLEAN', 2, 'BOOLEAN', 'true', 'EQ', '2020-12-25 04:08:33', '2020-12-25 04:08:33', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('消息金额大于10', null, 1, 2, 'lq', 0, '136', 'NUMBER', 2, 'NUMBER', '10', 'GT', '2021-01-15 09:16:05', '2020-12-28 02:48:22', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('消费金额大于2000', null, 1, 2, 'lq', 0, '125', 'NUMBER', 2, 'NUMBER', '2000', 'GT', '2021-01-11 06:10:09', '2021-01-11 06:10:09', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('条件1', null, 2, 2, 'lq', 1, '126', 'NUMBER', 2, 'NUMBER', '10', 'GT', '2021-01-12 03:35:01', '2021-01-12 03:35:01', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('出现人', null, 1, 2, 'lq', 0, '130', 'COLLECTION', 2, 'STRING', 'person', 'CONTAIN', '2021-01-13 10:42:45', '2021-01-13 10:42:45', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('出现武器', null, 1, 2, 'lq', 0, '130', 'COLLECTION', 2, 'STRING', 'weapon', 'CONTAIN', '2021-01-13 10:43:16', '2021-01-13 10:43:16', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('会员2测试', null, 1, 2, 'lq', 0, '135', 'NUMBER', 2, 'NUMBER', '4', 'GE', '2021-01-15 07:25:22', '2021-01-15 07:25:22', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('消费金额测试', null, 1, 2, 'lq', 0, '136', 'NUMBER', 2, 'NUMBER', '2000', 'GE', '2021-01-15 07:26:16', '2021-01-15 07:26:16', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('测试ws', null, 1, 2, 'lq', 0, '137', 'NUMBER', 2, 'NUMBER', '5', 'EQ', '2021-01-15 10:02:13', '2021-01-15 10:02:13', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('测试ws2', null, 1, 2, 'lq', 0, '137', 'NUMBER', 2, 'NUMBER', '8', 'EQ', '2021-01-15 10:06:29', '2021-01-15 10:06:29', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('小于50米阻车器开', '绞车小于阻车器50米那么开启阻车器', 1, 2, 'lq', 0, '138', 'NUMBER', 1, 'NUMBER', '135', 'LT', '2021-01-18 09:06:02', '2021-01-18 09:06:02', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('当绞车下行', null, 1, 2, 'lq', 0, '139', 'NUMBER', 1, 'NUMBER', '137', 'EQ', '2021-01-18 09:24:26', '2021-01-18 09:24:26', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('出现小汽车', null, 1, 2, 'lq', 0, '130', 'COLLECTION', 2, 'STRING', 'car', 'CONTAIN', '2021-01-19 01:08:24', '2021-01-19 01:08:24', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('温度大于37.3', null, 1, 2, 'lq', 0, '142', 'NUMBER', 2, 'NUMBER', '37.3', 'GT', '2021-01-19 07:49:19', '2021-01-19 07:49:19', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('时间间隔', null, 1, 2, 'lq', 0, '145', 'NUMBER', 2, 'NUMBER', '30', 'GE', '2021-01-21 09:27:54', '2021-01-21 09:25:05', 0);
INSERT INTO boot_engine.rule_engine_condition (name, description, workspace_id, create_user_id, create_user_name, left_type, left_value, left_value_type, right_type, right_value_type, right_value, symbol, update_time, create_time, deleted) VALUES ('速度大于60', null, 1, 2, 'lq', 0, '150', 'NUMBER', 2, 'NUMBER', '60', 'GT', '2021-01-23 10:18:18', '2021-01-23 10:18:18', 0);